package DCRS_CORBA;

/**
* DCRS_CORBA/DCRSInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/pulkitwadhwa/eclipse-workspace/RMI/src/CorbaInteface.idl
* Sunday, November 4, 2018 4:01:26 o'clock PM EST
*/

public final class DCRSInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public DCRS_CORBA.DCRSInterface value = null;

  public DCRSInterfaceHolder ()
  {
  }

  public DCRSInterfaceHolder (DCRS_CORBA.DCRSInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DCRS_CORBA.DCRSInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DCRS_CORBA.DCRSInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DCRS_CORBA.DCRSInterfaceHelper.type ();
  }

}
