package DCRS_CORBA;


/**
* DCRS_CORBA/DCRSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/pulkitwadhwa/eclipse-workspace/RMI/src/CorbaInteface.idl
* Sunday, November 4, 2018 4:01:26 o'clock PM EST
*/

public interface DCRSInterfaceOperations 
{
  boolean addCourse (String courseID, String semester, int capacity);
  boolean removeCourse (String courseID, String semester);
  String listCourseAvailability (String semester);
  boolean enrolCourse (String studentID, String courseID, String semester);
  String getClassSchedule (String studentID);
  boolean dropCourse (String studentID, String courseID);
  boolean swapCourse (String studentID, String oldcourseID, String newcourseID);
} // interface DCRSInterfaceOperations
