package DCRS_CORBA;


/**
* DCRS_CORBA/DCRSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/pulkitwadhwa/eclipse-workspace/RMI/src/CorbaInteface.idl
* Sunday, November 4, 2018 4:01:26 o'clock PM EST
*/

public interface DCRSInterface extends DCRSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCRSInterface
